# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/sm7675-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter avalon,$(TARGET_DEVICE)),)

endif
